# Generated by Django 6.1.1 on 2026-10-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_alter_lineitem_quantity_alter_lineitem_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
